function labels=svmlinGo(datafile, params)
    svmlin_path='~/Documents/MATLAB/svmlin/';
    if ~isfield(params,{'C'})
        params.C=0.001;
    end
    if ~isfield(params,{'U'})
        params.U=1;
    end
    if ~isfield(params,{'A'})
        params.A=2;
    end
    if ~isfield(params,{'R'})
        params.R=0.5;
    end
    svmlin_exe = ...
        ['./svmlin -A ',...
        int2str(params.A),...
        ' -W ',...
        num2str(params.C),...
        ' -U ',...
        int2str(params.U),...
        ' -R ',...
        num2str(params.R),...
        ' ',...
        datafile,...
        '.data ',...
        datafile,...
        '.label '];
    cd(svmlin_path);
    system(svmlin_exe);   
    svmres = [datafile,'.data.outputs'];
    labels=importdata(svmres);
    labels(labels>=0)=1;
    labels(labels<0)=0;
    % process results
    cd ~/repos/Huang/k3de/Impl/semiSVC/;
end
